spring:
  kafka:
    bootstrap-servers: kafka:29092
    
    producer:
      bootstrap-servers: kafka:29092
    
    consumer:
      bootstrap-servers: kafka:29092

server:
  port: 8083

logging:
  level:
    com.invest: DEBUG
